// <auto-generated />
using System;
using System.Runtime.InteropServices;

namespace Lumio.Engine.NativeLoader;

internal static class AbiConstants
{
    public const uint AbiVersion = 1;
    public const string EntrySymbol = "lumio_engine_get_api_v1";
    public const string DefinitionSha256 = "32f99c21329b064d18431e1d8ef1161f2e71c8fe5bf5eba9e933f99fdedb28de";
    public const uint VoxelMaxCellsPerReadRequest = 262144;
    public const uint VoxelMaxEntriesPerWriteBatch = 65536;
    public const uint VoxelCellOffsetYStride = 256;
    public const uint VoxelCellOffsetZStride = 16;
    public const uint VoxelCellOffsetXStride = 1;
}

internal enum VoxelPresence : uint
{
    Ready = 0,
    Unchanged = 1,
    Pending = 2,
    Unavailable = 3,
}

internal enum VoxelQueryResolution : uint
{
    Hit = 0,
    Miss = 1,
    Unresolved = 2,
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelSectionKey
{
    public int X;
    public byte Y;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
    public byte[] Reserved;
    public int Z;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelWorldCoordinate
{
    public int X;
    public byte Y;
    public int Z;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelBoxRequest
{
    public VoxelWorldCoordinate Min;
    public VoxelWorldCoordinate Max;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelColumnRequest
{
    public int X;
    public int Z;
    public byte MinY;
    public byte MaxY;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
    public byte[] Reserved;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelBlockReadCellResult
{
    public VoxelPresence Presence;
    public byte HasBlockId;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
    public byte[] Reserved;
    public uint BlockId;
    public ulong SectionRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelBlockReadResult
{
    public VoxelPresence Presence;
    public byte HasBlockId;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
    public byte[] Reserved;
    public uint BlockId;
    public ulong SectionRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelSectionRevisionResult
{
    public VoxelPresence Presence;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
    public byte[] Reserved;
    public ulong SectionRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelSectionSegment
{
    public VoxelSectionKey SectionKey;
    public VoxelPresence Presence;
    public ulong SectionRevision;
    public uint FirstResult;
    public uint ResultCount;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelBlockWriteEntry
{
    public VoxelSectionKey SectionKey;
    public ushort CellOffset;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
    public byte[] Reserved;
    public uint BlockId;
    public ulong ExpectedSectionRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelWriteReceipt
{
    public VoxelSectionKey SectionKey;
    public ulong UpToSectionRevision;
    public ulong WorldRevision;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelPinStatus
{
    public byte Ready;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)]
    public byte[] Reserved;
    public uint SectionCount;
    public uint ReadySectionCount;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelWorldPoint
{
    public float X;
    public float Y;
    public float Z;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelRaycastRequest
{
    public VoxelWorldPoint Origin;
    public VoxelWorldPoint Direction;
    public float MaxDistance;
    public uint MaterialMask;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelRaycastResult
{
    public VoxelQueryResolution Resolution;
    public VoxelSectionKey UnresolvedSection;
    public VoxelWorldCoordinate HitCell;
    public uint BlockId;
    public VoxelWorldPoint HitPoint;
    public VoxelWorldPoint HitNormal;
    public float TravelDistance;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelSweepRequest
{
    public VoxelWorldPoint Center;
    public VoxelWorldPoint HalfExtents;
    public VoxelWorldPoint Displacement;
    public uint MaterialMask;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelSweepResult
{
    public VoxelQueryResolution Resolution;
    public byte Collided;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
    public byte[] Reserved;
    public float TravelFraction;
    public VoxelSectionKey UnresolvedSection;
    public VoxelWorldCoordinate HitCell;
    public uint BlockId;
    public VoxelWorldPoint HitPoint;
    public VoxelWorldPoint HitNormal;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelOverlapRequest
{
    public VoxelWorldPoint Center;
    public VoxelWorldPoint HalfExtents;
    public uint MaterialMask;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelOverlapHit
{
    public VoxelWorldCoordinate Cell;
    public uint BlockId;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VoxelOverlapResult
{
    public VoxelQueryResolution Resolution;
    public VoxelSectionKey UnresolvedSection;
    public uint ActualCount;
    public byte Truncated;
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
    public byte[] Reserved;
}


[StructLayout(LayoutKind.Sequential)]
internal struct VoxelRootSlots
{
    public nint BlockReadCell;
    public nint BlockReadBox;
    public nint BlockReadColumn;
    public nint BlockWritePrepare;
    public nint BlockWriteCommit;
    public nint BlockWriteAbort;
    public nint SectionRevisionQuery;
    public nint ResidencyPinDeclare;
    public nint ResidencyPinRelease;
    public nint ResidencyPinStatus;
    public nint Raycast;
    public nint Sweep;
    public nint Overlap;
}

internal static class VoxelErrorCodes
{
    public const int UnknownSectionKey = 1000;
    public const int UnknownChunkKey = 1001;
    public const int SectionYOutOfRange = 1002;
    public const int CoordinateOutOfBounds = 1003;
    public const int SectionUnavailable = 1004;
    public const int StaleSectionRevision = 1005;
    public const int PaletteOverflow = 1006;
    public const int SectionEncodingMismatch = 1007;
    public const int SectionDigestMismatch = 1008;
    public const int DirtySectionNotDurable = 1009;
    public const int LightingInPayload = 1010;
    public const int ChunkCarriesData = 1011;
    public const int UnknownMaterialClass = 1012;
    public const int MaterialClassNotACellLane = 1013;
    public const int LiquidAutoPropagationUnsupported = 1014;
    public const int CrossMaterialFaceMerge = 1015;
    public const int EntityBindingMissing = 1016;
    public const int EntityBindingOrphan = 1017;
    public const int EntityBindingTypeMismatch = 1018;
    public const int EntityBindingNotSparse = 1019;
    public const int BusinessDataInPayload = 1020;
    public const int BindingCommitSplit = 1021;
    public const int BlockTypeScopeViolation = 1022;
    public const int SystemReservedTypeMisuse = 1023;
    public const int RoomLocalTypeWithoutMapping = 1024;
    public const int PlayerTypeDeclaresBehavior = 1025;
    public const int PaletteReclaimBeforeEscalation = 1026;
    public const int DeadPaletteEntryInPayload = 1027;
    public const int DeltaBaseRevisionMismatch = 1028;
    public const int DeltaUsedForFirstDelivery = 1029;
    public const int UnresolvedHitTreatedAsAir = 1030;
    public const int UnresolvedHitTreatedAsSolid = 1031;
    public const int QueryBufferOverflow = 1032;
    public const int QueryResultDivergence = 1033;
    public const int CollisionBehaviorNotFromMaterialTable = 1034;
    public const int QueryMutatesWorld = 1035;
    public const int WorldYOutOfRange = 1036;
    public const int BlockCatalogNotDense = 1037;
    public const int BlockCatalogNameReused = 1038;
    public const int BlockCatalogRowIncomplete = 1039;
    public const int ReadBudgetExceeded = 1040;
    public const int ReadResultMissingRevision = 1041;
    public const int WriteBatchTooLarge = 1042;
    public const int UnstructuredMutationEntry = 1043;
    public const int CellOffsetOutOfRange = 1044;
    public const int ResidencyPinExceedsBudget = 1045;
    public const int PinRegionNotReady = 1046;
    public const int PinnedSectionEvicted = 1047;
    public const int PinnedReadReturnedPending = 1048;
    public const int UnknownBehaviorTemplate = 1049;
    public const int CellReadMissingPresence = 1050;
    public const int UnregisteredBlockType = 1051;
    public const int WriteBatchPartiallyApplied = 1052;
    public const int BaseRevisionOnFullEncoding = 1053;
    public const int DegenerateQueryShape = 1054;
}


[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int BlockWritePrepareFn(nint world, ulong transactionId, nint entries, uint entryCount, out nint token);
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int RaycastFn(nint world, nint request, out VoxelRaycastResult result);
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int SweepFn(nint world, nint request, out VoxelSweepResult result);
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate int OverlapFn(nint world, nint request, nint hits, uint capacity, out VoxelOverlapResult result);
