/* Generated by eng/generate-abi.mjs. Do not edit. */
#ifndef LUMIO_ENGINE_H
#define LUMIO_ENGINE_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef int32_t lumio_status_t;
typedef uint32_t lumio_voxel_presence_t;
#define LUMIO_VOXEL_READY ((lumio_voxel_presence_t)0u)
#define LUMIO_VOXEL_UNCHANGED ((lumio_voxel_presence_t)1u)
#define LUMIO_VOXEL_PENDING ((lumio_voxel_presence_t)2u)
#define LUMIO_VOXEL_UNAVAILABLE ((lumio_voxel_presence_t)3u)

#define LUMIO_VOXEL_MAX_CELLS_PER_READ_REQUEST 262144u
#define LUMIO_VOXEL_MAX_ENTRIES_PER_WRITE_BATCH 65536u
#define LUMIO_VOXEL_CELL_OFFSET_Y_STRIDE 256u
#define LUMIO_VOXEL_CELL_OFFSET_Z_STRIDE 16u
#define LUMIO_VOXEL_CELL_OFFSET_X_STRIDE 1u

#define VOXEL_ERROR_UNKNOWN_SECTION_KEY 1000
#define VOXEL_ERROR_UNKNOWN_CHUNK_KEY 1001
#define VOXEL_ERROR_SECTION_Y_OUT_OF_RANGE 1002
#define VOXEL_ERROR_COORDINATE_OUT_OF_BOUNDS 1003
#define VOXEL_ERROR_SECTION_UNAVAILABLE 1004
#define VOXEL_ERROR_STALE_SECTION_REVISION 1005
#define VOXEL_ERROR_PALETTE_OVERFLOW 1006
#define VOXEL_ERROR_SECTION_ENCODING_MISMATCH 1007
#define VOXEL_ERROR_SECTION_DIGEST_MISMATCH 1008
#define VOXEL_ERROR_DIRTY_SECTION_NOT_DURABLE 1009
#define VOXEL_ERROR_LIGHTING_IN_PAYLOAD 1010
#define VOXEL_ERROR_CHUNK_CARRIES_DATA 1011
#define VOXEL_ERROR_UNKNOWN_MATERIAL_CLASS 1012
#define VOXEL_ERROR_MATERIAL_CLASS_NOT_A_CELL_LANE 1013
#define VOXEL_ERROR_LIQUID_AUTO_PROPAGATION_UNSUPPORTED 1014
#define VOXEL_ERROR_CROSS_MATERIAL_FACE_MERGE 1015
#define VOXEL_ERROR_ENTITY_BINDING_MISSING 1016
#define VOXEL_ERROR_ENTITY_BINDING_ORPHAN 1017
#define VOXEL_ERROR_ENTITY_BINDING_TYPE_MISMATCH 1018
#define VOXEL_ERROR_ENTITY_BINDING_NOT_SPARSE 1019
#define VOXEL_ERROR_BUSINESS_DATA_IN_PAYLOAD 1020
#define VOXEL_ERROR_BINDING_COMMIT_SPLIT 1021
#define VOXEL_ERROR_BLOCK_TYPE_SCOPE_VIOLATION 1022
#define VOXEL_ERROR_SYSTEM_RESERVED_TYPE_MISUSE 1023
#define VOXEL_ERROR_ROOM_LOCAL_TYPE_WITHOUT_MAPPING 1024
#define VOXEL_ERROR_PLAYER_TYPE_DECLARES_BEHAVIOR 1025
#define VOXEL_ERROR_PALETTE_RECLAIM_BEFORE_ESCALATION 1026
#define VOXEL_ERROR_DEAD_PALETTE_ENTRY_IN_PAYLOAD 1027
#define VOXEL_ERROR_DELTA_BASE_REVISION_MISMATCH 1028
#define VOXEL_ERROR_DELTA_USED_FOR_FIRST_DELIVERY 1029
#define VOXEL_ERROR_UNRESOLVED_HIT_TREATED_AS_AIR 1030
#define VOXEL_ERROR_UNRESOLVED_HIT_TREATED_AS_SOLID 1031
#define VOXEL_ERROR_QUERY_BUFFER_OVERFLOW 1032
#define VOXEL_ERROR_QUERY_RESULT_DIVERGENCE 1033
#define VOXEL_ERROR_COLLISION_BEHAVIOR_NOT_FROM_MATERIAL_TABLE 1034
#define VOXEL_ERROR_QUERY_MUTATES_WORLD 1035
#define VOXEL_ERROR_WORLD_Y_OUT_OF_RANGE 1036
#define VOXEL_ERROR_BLOCK_CATALOG_NOT_DENSE 1037
#define VOXEL_ERROR_BLOCK_CATALOG_NAME_REUSED 1038
#define VOXEL_ERROR_BLOCK_CATALOG_ROW_INCOMPLETE 1039
#define VOXEL_ERROR_READ_BUDGET_EXCEEDED 1040
#define VOXEL_ERROR_READ_RESULT_MISSING_REVISION 1041
#define VOXEL_ERROR_WRITE_BATCH_TOO_LARGE 1042
#define VOXEL_ERROR_UNSTRUCTURED_MUTATION_ENTRY 1043
#define VOXEL_ERROR_CELL_OFFSET_OUT_OF_RANGE 1044
#define VOXEL_ERROR_RESIDENCY_PIN_EXCEEDS_BUDGET 1045
#define VOXEL_ERROR_PIN_REGION_NOT_READY 1046
#define VOXEL_ERROR_PINNED_SECTION_EVICTED 1047
#define VOXEL_ERROR_PINNED_READ_RETURNED_PENDING 1048
#define VOXEL_ERROR_UNKNOWN_BEHAVIOR_TEMPLATE 1049
#define VOXEL_ERROR_CELL_READ_MISSING_PRESENCE 1050
#define VOXEL_ERROR_UNREGISTERED_BLOCK_TYPE 1051
#define VOXEL_ERROR_WRITE_BATCH_PARTIALLY_APPLIED 1052
#define VOXEL_ERROR_BASE_REVISION_ON_FULL_ENCODING 1053

typedef uint32_t lumio_voxel_query_resolution_t;
#define LUMIO_VOXEL_QUERY_HIT ((lumio_voxel_query_resolution_t)0u)
#define LUMIO_VOXEL_QUERY_MISS ((lumio_voxel_query_resolution_t)1u)
#define LUMIO_VOXEL_QUERY_UNRESOLVED ((lumio_voxel_query_resolution_t)2u)

typedef struct lumio_voxel_section_key_t {
    int32_t x;
    uint8_t y;
    uint8_t _reserved[3];
    int32_t z;
} lumio_voxel_section_key_t;

typedef struct lumio_voxel_world_coordinate_t {
    int32_t x;
    uint8_t y;
    int32_t z;
} lumio_voxel_world_coordinate_t;

typedef struct lumio_voxel_box_request_t {
    lumio_voxel_world_coordinate_t min;
    lumio_voxel_world_coordinate_t max;
} lumio_voxel_box_request_t;

typedef struct lumio_voxel_column_request_t {
    int32_t x;
    int32_t z;
    uint8_t min_y;
    uint8_t max_y;
    uint8_t _reserved[2];
} lumio_voxel_column_request_t;

typedef struct lumio_voxel_block_read_cell_result_t {
    lumio_voxel_presence_t presence;
    uint8_t has_block_id;
    uint8_t _reserved[3];
    uint32_t block_id;
    uint64_t section_revision;
} lumio_voxel_block_read_cell_result_t;

typedef struct lumio_voxel_block_read_result_t {
    lumio_voxel_presence_t presence;
    uint8_t has_block_id;
    uint8_t _reserved[3];
    uint32_t block_id;
    uint64_t section_revision;
} lumio_voxel_block_read_result_t;

typedef struct lumio_voxel_section_revision_result_t {
    lumio_voxel_presence_t presence;
    uint8_t _reserved[4];
    uint64_t section_revision;
} lumio_voxel_section_revision_result_t;

typedef struct lumio_voxel_section_segment_t {
    lumio_voxel_section_key_t section_key;
    lumio_voxel_presence_t presence;
    uint64_t section_revision;
    uint32_t first_result;
    uint32_t result_count;
} lumio_voxel_section_segment_t;

typedef struct lumio_voxel_block_write_entry_t {
    lumio_voxel_section_key_t section_key;
    uint16_t cell_offset;
    uint8_t _reserved[2];
    uint32_t block_id;
    uint64_t expected_section_revision;
} lumio_voxel_block_write_entry_t;

typedef struct lumio_voxel_write_receipt_t {
    lumio_voxel_section_key_t section_key;
    uint64_t up_to_section_revision;
    uint64_t world_revision;
} lumio_voxel_write_receipt_t;

typedef struct lumio_voxel_pin_status_t {
    uint8_t ready;
    uint8_t _reserved[7];
    uint32_t section_count;
    uint32_t ready_section_count;
} lumio_voxel_pin_status_t;

typedef struct lumio_voxel_world_point_t {
    float x;
    float y;
    float z;
} lumio_voxel_world_point_t;

typedef struct lumio_voxel_raycast_request_t {
    lumio_voxel_world_point_t origin;
    lumio_voxel_world_point_t direction;
    float max_distance;
    uint32_t material_mask;
} lumio_voxel_raycast_request_t;

typedef struct lumio_voxel_raycast_result_t {
    lumio_voxel_query_resolution_t resolution;
    lumio_voxel_section_key_t unresolved_section;
    lumio_voxel_world_coordinate_t hit_cell;
    uint32_t block_id;
    lumio_voxel_world_point_t hit_point;
    lumio_voxel_world_point_t hit_normal;
    float travel_distance;
} lumio_voxel_raycast_result_t;

typedef struct lumio_voxel_sweep_request_t {
    lumio_voxel_world_point_t center;
    lumio_voxel_world_point_t half_extents;
    lumio_voxel_world_point_t displacement;
    uint32_t material_mask;
} lumio_voxel_sweep_request_t;

typedef struct lumio_voxel_sweep_result_t {
    lumio_voxel_query_resolution_t resolution;
    uint8_t collided;
    uint8_t _reserved[3];
    float travel_fraction;
    lumio_voxel_section_key_t unresolved_section;
    lumio_voxel_world_coordinate_t hit_cell;
    uint32_t block_id;
    lumio_voxel_world_point_t hit_point;
    lumio_voxel_world_point_t hit_normal;
} lumio_voxel_sweep_result_t;

typedef struct lumio_voxel_overlap_request_t {
    lumio_voxel_world_point_t center;
    lumio_voxel_world_point_t half_extents;
    uint32_t material_mask;
} lumio_voxel_overlap_request_t;

typedef struct lumio_voxel_overlap_hit_t {
    lumio_voxel_world_coordinate_t cell;
    uint32_t block_id;
} lumio_voxel_overlap_hit_t;

typedef struct lumio_voxel_overlap_result_t {
    lumio_voxel_query_resolution_t resolution;
    lumio_voxel_section_key_t unresolved_section;
    uint32_t actual_count;
    uint8_t truncated;
    uint8_t _reserved[3];
} lumio_voxel_overlap_result_t;

typedef lumio_status_t (*lumio_block_read_cell_fn)(void*, const lumio_voxel_world_coordinate_t*, lumio_voxel_block_read_cell_result_t*);
typedef lumio_status_t (*lumio_block_read_batch_fn)(void*, const void*, lumio_voxel_block_read_result_t*, uint32_t, uint32_t*, lumio_voxel_section_segment_t*, uint32_t, uint32_t*, uint8_t*);
typedef lumio_status_t (*lumio_block_write_prepare_fn)(void*, uint64_t, const lumio_voxel_block_write_entry_t*, uint32_t, void**);
typedef lumio_status_t (*lumio_block_write_commit_fn)(void*, void*, lumio_voxel_write_receipt_t*, uint32_t, uint32_t*);
typedef lumio_status_t (*lumio_block_write_abort_fn)(void*, void*);
typedef lumio_status_t (*lumio_section_revision_query_fn)(void*, const lumio_voxel_section_key_t*, lumio_voxel_section_revision_result_t*);
typedef lumio_status_t (*lumio_residency_pin_declare_fn)(void*, const lumio_voxel_section_key_t*, uint32_t, uint32_t, void**);
typedef lumio_status_t (*lumio_residency_pin_release_fn)(void*, void*);
typedef lumio_status_t (*lumio_residency_pin_status_fn)(void*, void*, lumio_voxel_pin_status_t*);
typedef lumio_status_t (*lumio_raycast_fn)(void*, const lumio_voxel_raycast_request_t*, lumio_voxel_raycast_result_t*);
typedef lumio_status_t (*lumio_sweep_fn)(void*, const lumio_voxel_sweep_request_t*, lumio_voxel_sweep_result_t*);
typedef lumio_status_t (*lumio_overlap_fn)(void*, const lumio_voxel_overlap_request_t*, lumio_voxel_overlap_hit_t*, uint32_t, lumio_voxel_overlap_result_t*);

/* The root declaration is emitted from the validated native-abi.json root field model. */
typedef struct lumio_engine_root_api_v1_t {
    uint32_t abi_version;
    uint32_t struct_size;
    uint8_t abi_hash[32];
    uint8_t build_id[16];
    void* ping;
    void* create_clr_host;
    void* clr_host_call;
    void* destroy_clr_host;
    void* timer_create_manager;
    void* timer_destroy_manager;
    void* timer_register_dispatch;
    void* timer_register_scope;
    void* timer_teardown_scope;
    void* timer_create_slot;
    void* timer_bind_slot;
    void* timer_close_slot;
    void* timer_schedule_one_shot;
    void* timer_schedule_repeating;
    void* timer_cancel;
    void* timer_advance;
    void* timer_pump;
    void* timer_drain;
    lumio_block_read_cell_fn block_read_cell;
    lumio_block_read_batch_fn block_read_box;
    lumio_block_read_batch_fn block_read_column;
    lumio_block_write_prepare_fn block_write_prepare;
    lumio_block_write_commit_fn block_write_commit;
    lumio_block_write_abort_fn block_write_abort;
    lumio_section_revision_query_fn section_revision_query;
    lumio_residency_pin_declare_fn residency_pin_declare;
    lumio_residency_pin_release_fn residency_pin_release;
    lumio_residency_pin_status_fn residency_pin_status;
    lumio_raycast_fn raycast;
    lumio_sweep_fn sweep;
    lumio_overlap_fn overlap;
} lumio_engine_root_api_v1_t;

lumio_status_t lumio_engine_get_api_v1(uint32_t requested_version, const lumio_engine_root_api_v1_t** out_api);

#ifdef __cplusplus
}
#endif
#endif /* LUMIO_ENGINE_H */
